- name: run ios_facts on routers
  hosts: cisco_routers

  tasks:
    - name: run ios_facts
      ios_facts:
        gather_subset: all
      register: ios_facts_result

    - name: show ansible_net_all_ipv4_addresses fact
      debug: var=ansible_net_all_ipv4_addresses

    - name: show ansible_net_interfaces fact
      debug: var=ansible_net_interfaces['Ethernet0/0']

    - name: create all_facts dir
      file:
        path: ./all_facts/
        state: directory
        mode: 0755
    
    - name: Copy facts to files
      copy:
        content: "{{ ios_facts_result | to_nice_json }}"
        dest: "all_facts/{{inventory_hostname}}_facts.json"

