- name: Run show commands on routers # this is known as a play, multiple plays contitute a playbook
  hosts: cisco_routers # this is the devices on which the play will be executed
  gather_facts: false # this disables facts gathering which ansible does by default

  tasks:
    - name: run show ip int brief # this is a task within a play, it is executed in the order its defined.
      ios_command: # this is a mandatory item in a task, to define the module to be used in the task
        commands: show ip int brief # this is a mandatory item in "ios_command" module
    
    - name: run show ip arp
      ios_command:
        commands: show ip arp

- name: Run command on R1
  hosts: 192.168.0.149
  gather_facts: false

  tasks:
    - name: runn show int status
      ios_command:
        commands: show clock
